name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: RUSTFLAGS="-C target-feature=+aes" cargo build --verbose
    - name: Install dependencies
      run: |
        sudo chown $(whoami) /dev/kvm
        sudo apt update
        sudo apt install -y qemu-system-x86 xorriso ncat bzip2
    - name: Test data setup
      run: |
        cd test-data
        ./setup.sh
    - name: Test img-luks-pg100-read
      run: |
        cd test-data
        ./mk-img-test-luks-pg100.sh
        cargo test --test test_img_luks_pg100_read
    - name: Test img-luks-pg100-write
      run: |
        cd test-data
        ./mk-img-test-luks-blank.sh
        cargo test --test test_img_luks_pg100_write test_write_device
        cargo test --test test_img_luks_pg100_write test_read_device
        ./decrypt-test-luks-write.sh
        cargo test --test test_img_luks_pg100_write test_verify_decryption
